### ISSUE TITLE
Investigate why the store is getting slower

### ISSUE THREAD

**Issue by white-gecko** [AKSW/QuitStore#66]
Investigate why the store is getting slower after running multiple queries

**Comment by Kyrosh** [comment]
For documentation:

The store was getting slower because of the following reasons:
- search for the blobs of a commit (required file access via pygit2)
 - search time reduced by adding a lookup of needed blobs from an index
 - index is updated if no entry was found or during commit
- copy graphs on edit
 - was done to keep old blobs in cache
 - blobs are no longer copied and removed from cache on modification
 - blobs need to be reloaded once removed from cache
- sorting and serializing full graphs not only parts:
 - problem still remains

**Comment by Kyrosh** [comment]
To restore the ordered serialization and to speed things up, since f50cc25 a FileCache is stored along each deserialized graph. Only deltas are applied to the FileCache. Serialization therefore becomes a concat and write operation of an already sorted list.

**Comment by white-gecko** [comment]
Currently I'm running benchmarks. for 500 runs already looks good. Currently I'm running it 2000 runs.
[bsbm.pdf](https://github.com/AKSW/QuitStore/files/1355483/bsbm.pdf)
