### ISSUE TITLE
Feature Request: stop quit process manually

### ISSUE THREAD

**Issue by k00ni** [AKSW/QuitStore#84]
I am using quit inside a Docker container and would like to stop it manually.

Here is some pseudo code:

```bash
quit --configfile $CONFIGFILE --port $PORT &

# do something

quit stop
```

For the moment, i would use `pkill` or `killall` as a "workaround".

Thanks

**Comment by white-gecko** [comment]
This would not work, since the quit process will continue running because it is a server. If you want to stop it, while it is running in the foreground, just hit ctrl+c. If you are not attached to the quit process with your interactive terminal you can send a terminate signal to it, e.g. using kill or the commands you are mentioning above.
